### ISSUE TITLE
Clicking on the next page in long strip sometimes doesn't scroll the page

### ISSUE THREAD

**Issue by Pyreko** [Matriz88/hef-website#37]
If I'm on page one in long-strip mode, sometimes I can click once and it'll say I'm on page 2, but the page won't scroll until I click again, and it pops me on page 3.

![image](https://github.com/Matriz88/hef-website/assets/25498386/fcfef217-eb1f-49bd-b64a-e88c24104700)

**Comment by Hiroreco** [comment]
That's weird, is the bug consistent? I can't seem to reproduce it (using the viewport you gave me in the other pr)

**Comment by Pyreko** [comment]
I think it's resolved by #35 anyways.

**Comment by Pyreko** [comment]
Nope, never mind - I can still reproduce it. I'll try and fix it.

**Comment by Hiroreco** [comment]
Yeah I also just got it, another thing to keep in mind when you're fixing this is that whenever the page refreshes, the scrollbar isn't set to the correct page (since we're able to save progress now). Probably because the pages haven't finished loading yet so it can't set the scrollbar correctly.
- Supposed to be on page 5 but is set to page 1
![image](https://github.com/Matriz88/hef-website/assets/61302586/6dcc7b11-66d8-43bf-9760-bc0991234046)
